Retropie desktop app
Botspot/pi-apps pull request #132
Opened 2020-12-11 21:05 UTC by mobilegmYT

@Botspot

2020-12-12 05:45 UTC, fabianmendes requested changes
I think this is not correct, or it actually is?

2020-12-12 05:47 UTC, fabianmendes commented on apps/Retropie/install
> +Terminal=true' > ~/.local/share/applications/retropie.desktop
=false

2020-12-12 15:12 UTC, Botspot commented
> I think this is not correct, or it actually is?

It's not correct. You're right.

2020-12-18 16:22 UTC, mobilegmYT commented
🤷‍♂️ I found this from TwisterOS, so it should work on rpi os. Might be wrong though.

2021-01-28 16:39 UTC, Botspot commented
The syntax used for echoing was not correct. In any case, this PR is being closed because somebody will get 5 dollars for improving the RetroPie app.

2021-01-28 16:39 UTC, closed without merging