Added support for arm64 platforms
Botspot/pi-apps pull request #409
Opened 2021-03-03 16:28 UTC by Jai-JAP

Added support for arm64 platforms (As per box86 updated CMakeLists.txt)  -DRPI4ARM64 flag is not included in Compile.md Instructions

2021-03-03 16:43 UTC, Itai-Nelken commented
you should use pi-apps `pkg-install` script to install the dependencies.

2021-03-03 17:24 UTC, Jai-JAP commented
> you should use pi-apps `pkg-install` script to install the dependencies.
> and add the `purge-installed` line to the uninstall script if the arch is arm64.

2021-03-03 17:28 UTC, Itai-Nelken commented
why did you close this?

2021-03-03 17:29 UTC, Jai-JAP commented
> you should use pi-apps `pkg-install` script to install the dependencies.
> and add the `purge-installed` line to the uninstall script if the arch is arm64.

Present uninstall script works fine for arm64  as well

2021-03-03 17:35 UTC, Itai-Nelken commented
>Present uninstall script works fine for arm64 as well

@Jai-JAP yes to uninstall box86 but not to uninstall the dependencies you installed to compile box86.

2021-03-03 17:35 UTC, Jai-JAP commented
> @Jai-JAP why did you close this?

Sorry it happened accidentally

2021-03-03 17:39 UTC, Itai-Nelken commented on apps/Box86/install-64
> +"${DIRECTORY}/pkg-install" "gcc-arm-linux-gnueabihf" || exit 1
add this package (`gcc-arm-linux-gbueabihf`) to the 2 lines above, I don't think you can run `pkg-install` multiple times one after the other.

2021-03-03 17:39 UTC, Itai-Nelken commented on apps/Box86/install-64
> +"${DIRECTORY}/pkg-install" "cmake" "$(dirname "$0")" || exit 1
same as my above comment.

2021-03-03 17:40 UTC, Itai-Nelken commented on apps/Box86/install-64
> +make -j4 || error "make failed!"
add this instead:
```bash
cores="$(nproc)"
make -j$cores
```
to stop pi3's from failing because they run out of memory.

2021-03-03 17:41 UTC, Itai-Nelken requested changes
added a few suggestions

2021-03-03 17:45 UTC, Itai-Nelken commented
also add this code to the uninstall script:
```bash
if [ ! -z "$(file "$(readlink -f "/sbin/init")" | grep 64)" ];then
    "${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 1
elif [ ! -z "$(file "$(readlink -f "/sbin/init")" | grep 32)" ];then
    sleep 0.00001
else
    error "Can't detect OS architecture! something is very wrong!"
fi
```
it will uninstall all the packages `pkg-install` installed, but only if you are on a 64bit OS.

2021-03-03 17:51 UTC, Itai-Nelken commented on apps/Box86/uninstall
> +CODENAME=$(lsb_release -cs)
no, thast not how `purge-installed` works (I made the same mistake once), use this instead:
```bash
if [ ! -z "$(file "$(readlink -f "/sbin/init")" | grep 64)" ]; then
    "${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 1
elif [ ! -z "$(file "$(readlink -f "/sbin/init")" | grep 32)" ]; then
    sleep 0.00001
else
    error "Can't detect OS architecture! something is very wrong!"
fi
```

2021-03-03 17:52 UTC, Itai-Nelken requested changes
fix `purge-installed`

2021-03-03 17:52 UTC, Itai-Nelken commented on apps/Box86/uninstall
> +  "${DIRECTORY}/purge-installed" "libc6:armhf  libx11-6:armhf  libgdk-pixbuf2.0-0:armhf libgtk2.0-0:armhf libstdc++6:armhf libsdl2-2.0-0:armhf mesa-va-drivers:armhf libsdl1.2-dev:armhf libsdl-mixer1.
no, thast not how `purge-installed` works (I made the same mistake once), use this instead:
```bash
if [ ! -z "$(file "$(readlink -f "/sbin/init")" | grep 64)" ]; then
    "${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 1
elif [ ! -z "$(file "$(readlink -f "/sbin/init")" | grep 32)" ]; then
    sleep 0.00001
else
    error "Can't detect OS architecture! something is very wrong!"
fi
```

2021-03-03 17:54 UTC, Itai-Nelken commented on apps/Box86/uninstall
> +  "${DIRECTORY}/purge-installed" "libc6:armhf  libx11-6:armhf  libgdk-pixbuf2.0-0:armhf libgtk2.0-0:armhf libstdc++6:armhf libsdl2-2.0-0:armhf mesa-va-drivers:armhf libsdl1.2-dev:armhf libsdl-mixer1.
no, thats not how `purge-installed` works (I made the same mistake once), use this instead:
```bash
if [ ! -z "$(file "$(readlink -f "/sbin/init")" | grep 64)" ]; then
    "${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 1
elif [ ! -z "$(file "$(readlink -f "/sbin/init")" | grep 32)" ]; then
    sleep 0.00001
else
    error "Can't detect OS architecture! something is very wrong!"
fi
```

2021-03-03 18:07 UTC, Itai-Nelken commented
@Jai-JAP you didn't understand how `purge-installed` works, you **don't** tell it what packages to remove, it knows what packages `pkg-install` installed, and uninstalls them.
again, use this in the uninstall script:
```bash
if [ ! -z "$(file "$(readlink -f "/sbin/init")" | grep 64)" ]; then
    "${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 1
elif [ ! -z "$(file "$(readlink -f "/sbin/init")" | grep 32)" ]; then
    sleep 0.00001
else
    error "Can't detect OS architecture! something is very wrong!"
fi
```

2021-03-05 02:31 UTC, mobilegmYT commented
Correct me if I'm wrong, but box86 needs a 32-bit toolchain to work, and you need a chroot for that.

2021-03-05 07:10 UTC, Itai-Nelken commented
> Correct me if I'm wrong, but box86 needs a 32-bit toolchain to work, and you need a chroot for that.

multiarch works as well.

2021-03-05 14:39 UTC, mobilegmYT commented
> > Correct me if I'm wrong, but box86 needs a 32-bit toolchain to work, and you need a chroot for that.
> 
> multiarch works as well.

Oh that works? Whenever someone talked about running it on 64-bit they said to chroot in the discord.

2021-03-05 14:43 UTC, Itai-Nelken commented
> > > Correct me if I'm wrong, but box86 needs a 32-bit toolchain to work, and you need a chroot for that.
> > 
> > 
> > multiarch works as well.
> 
> Oh that works? Whenever someone talked about running it on 64-bit they said to chroot in the discord.

works for me on Ubuntu 20.10

2021-03-05 15:17 UTC, Itai-Nelken requested changes
suggestion

2021-03-05 15:17 UTC, Itai-Nelken commented on apps/BalenaEtcher/install-32
> +rm -f ./etcher_1.5.114_armv7l.deb
I suggest you do this:
```suggestion
rm -f etcher*armv7l.deb
```

2021-03-05 15:17 UTC, mobilegmYT commented
@Jai-JAP Please make a separate pull request for other apps, and also v1.1.115 isn't in itai's repo.

2021-03-05 15:18 UTC, Itai-Nelken commented
also @Jai-JAP, this pr is for box86 on arm64, don't add etcher to it.

2021-03-18 04:32 UTC, Jai-JAP commented
Box86 for arm64 [scripts](https://github.com/Botspot/pi-apps/tree/master/apps/Box86) (install-64 & updated uninstall scripts) by @Itai-Nelken have been added.
Closing this pull request.

2021-03-24 21:33 UTC, JulyIghor commented
Not working on Ubuntu arm64, still tries to install armhf lib versions

2021-03-24 22:12 UTC, Itai-Nelken commented
> Not working on Ubuntu groovy arm64, still tries to install armhf lib versions

thats what its supposed to do, also pi-apps already added box86 on 64bit in #452.


box86 only works on armhf, so to run it on arm64 multiarch is used to install the armhf dependencies and box86.

2021-03-24 22:18 UTC, JulyIghor commented
> > Not working on Ubuntu groovy arm64, still tries to install armhf lib versions
> 
> thats what its supposed to do, also pi-apps already added box86 on 64bit in #452.
> 
> box86 only works on armhf, so to run it on arm64 multiarch is used to install the armhf dependencies and box86.

Ok, thanks for the answer

2021-03-25 05:36 UTC, closed without merging