Add cura stl thumbnails
Botspot/pi-apps pull request #705
Opened 2021-06-01 20:02 UTC by mobilegmYT

Installs https://github.com/unlimitedbacon/stl-thumb which adds thumbnails to stls in file manager.

2021-06-02 17:02 UTC, Itai-Nelken commented
Will wait for @Botspot for this one

2021-06-07 04:03 UTC, Botspot commented
Three things I notice:

1. I don't believe the 3rd-party Cura appimage **accepts arguments** for files to open. This fact makes any filetypes or icons fairly useless because you wouldn't be able to double-click a STL file to open it in Cura.
2. The script does not delete the deb file after installing it.
3. What if the user already had `stl-thumb` installed prior to this? (Hint: use `pkg-install` to install the local deb)

2021-06-07 04:12 UTC, mobilegmYT commented
> 3. What if the user already had `stl-thumb` installed prior to this? (Hint: use `pkg-install` to install the local deb)
Can pkg-install parse deb files?

2021-06-07 04:37 UTC, Itai-Nelken commented
> Can pkg-install parse deb files?

Yes

2021-06-07 04:37 UTC, Itai-Nelken commented
> Can pkg-install parse deb files?

Yes

2021-06-07 04:42 UTC, Itai-Nelken requested changes

2021-06-07 04:42 UTC, Itai-Nelken commented on apps/Cura/install-64
> +"${DIRECTORY}/pkg-install" "./stl-thumb_0.4.0_arm64.deb" "$(dirname "$0")" || exit 1
```suggestion
"${DIRECTORY}/pkg-install" "~/stl-thumb_0.4.0_arm64.deb" "$(dirname "$0")" || exit 1
```

2021-06-07 04:42 UTC, Itai-Nelken commented on apps/Cura/install-32
> +sudo apt install -y ./stl-thumb_0.4.0_armhf.deb
Use pkg-install here as well

2021-06-07 23:42 UTC, Botspot commented
@Itai-Nelken, I'm not sure that `pkg-install` is capable of parsing input files beginning with `./`. Was your change tested?

More importantly, I consider this PR rather useless as long as Cura cannot accept file inputs.

2021-06-07 23:43 UTC, mobilegmYT commented
Closin then.

2021-06-07 23:45 UTC, Botspot commented
> as long as Cura cannot accept file inputs.

Oh wait, it looks like Cura had an update and now it does accept file arguments.

2021-06-07 23:46 UTC, mobilegmYT commented
> > as long as Cura cannot accept file inputs.
> 
> Oh wait, it looks like Cura had an update and now it does accept file arguments.

*wheeze*

2021-06-07 23:47 UTC, Botspot commented
Looks like the Cura desktop file needs modifying to work. (inserting a %F somewhere)

2021-06-08 02:26 UTC, Botspot commented
> Looks like the Cura desktop file needs modifying to work. (inserting a %F somewhere)

Finally.
```
Exec=bash -c 'sudo modprobe fuse; ~/Cura.AppImage '\ "%f"
```
This was roughly my 25th attempt. All previous attempts either failed to open the file, failed to open Cura, or failed to work for filenames containing a space character.

2021-06-08 03:39 UTC, Itai-Nelken commented
>@Itai-Nelken, I'm not sure that pkg-install is capable of parsing input files beginning with ./. Was your change tested?

`$(pwd)` works or the full path also works. I think that `~/` also works.

2021-06-21 15:04 UTC, Botspot commented
d105473d9f5d95f6e3f1e737cacdd6a5a10e3f50

2021-06-21 15:04 UTC, closed without merging