Add 64bit support for sublime text (using official arm64 binaries)
Botspot/pi-apps pull request #707
Opened 2021-06-02 16:00 UTC by Itai-Nelken

Sublime text now have official Linux (and MacOS) arm64 binaries! unfortunately armhf OS's will have to stay with sublime text 2 running with box86 while 64bit OS's get sublime text 4 running natively.
**the script is not tested, testers needed.**

2021-06-22 21:21 UTC, finitelife requested changes
Why install a static version when the Deb is available? 

```bash
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -

sudo apt install apt-transport-https

echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list

sudo apt update

sudo apt install sublime-text
```

2021-06-24 15:19 UTC, Itai-Nelken commented
I have had problems with their repo in the past, but I'll take a look if it works fine now.

2021-07-20 10:03 UTC, Itai-Nelken commented
@Botspot what do you think is better:
1) not using the `apt` repo - we need to update manually but installation is more foolproof.
2) using the `apt` repo - automatic updates but there are chances of apt getting messed up.

2021-07-22 18:56 UTC, chunky-milk commented
I just tested the apt repo, works fine

2021-07-24 21:48 UTC, Botspot commented
> @Botspot what do you think is better:
> 
> 1. not using the `apt` repo - we need to update manually but installation is more foolproof.
> 2. using the `apt` repo - automatic updates but there are chances of apt getting messed up.

In this case, I see no problem with using the apt repo, because we've done that before.
Just make sure that it's done cleanly. (Example: use a sources.list.d file, and if apt signing fails, delete the .list file before the script exits with failure)

2021-07-25 21:24 UTC, Botspot commented
https://github.com/Botspot/pi-apps/commit/876722f1697fd5f05d7b6b36e5d0c51243738436

2021-07-25 21:24 UTC, closed without merging